volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local
#  rabbitmq-data:
#    driver: local
services:
  postgres-db:
    restart: unless-stopped
    image: postgres:15
    environment:
      POSTGRES_DB: skills_hub
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      #      - MYSQL_ROOT_PASSWORD=
      #      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      #      - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max-connections=1000 --log_error --log_warnings=4 --slow-query-log --log-queries-not-using-indexes --min-examined-row-limit=100
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    #      - mariabd-data:/var/lib/mysql
    container_name: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root" ]
      interval: 3s
      retries: 10

  minio:
    restart: unless-stopped
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # console web
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"




#  rabbitmq:
#    restart: unless-stopped
#    build: rabbitmq
#    image: rabbitmq_with_delayed_message_exchange
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - rabbitmq-data:/var/lib/rabbitmq
#    container_name: rabbitmq




