volumes:
  postgres-course-data:
    driver: local
  postgres-storage-data:
    driver: local
  minio-data:
    driver: local
# todo to init rabbit
#  rabbitmq-data:
#    driver: local
services:
  #  postgres-db:
  #    restart: unless-stopped
  #    image: postgres:15
  #    environment:
  #      POSTGRES_DB: skills_hub
  #      POSTGRES_USER: root
  #      POSTGRES_PASSWORD: root
  #    ports:
  #      - "5433:5432"
  #    volumes:
  #      - postgres-data:/var/lib/postgresql/data
  #    #      - mariabd-data:/var/lib/mysql
  #    container_name: postgres
  #    healthcheck:
  #      test: [ "CMD", "pg_isready", "-U", "root" ]
  #      interval: 3s
  #      retries: 10
  postgres-course:
    image: postgres:15
    container_name: postgres-course
    environment:
      POSTGRES_DB: course_service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres-course-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d course_service" ]
      interval: 3s
      retries: 10

  postgres-storage:
    image: postgres:15
    container_name: postgres-storage
    environment:
      POSTGRES_DB: storage_service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - postgres-storage-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d storage_service" ]
      interval: 3s
      retries: 10

  minio:
    restart: unless-stopped
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # console web
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"


#todo to init rabbit
#  rabbitmq:
#    restart: unless-stopped
#    build: rabbitmq
#    image: rabbitmq_with_delayed_message_exchange
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - rabbitmq-data:/var/lib/rabbitmq
#    container_name: rabbitmq




