##############################################################################################################################################################################
# SERVER
##############################################################################################################################################################################
server.port=10020
##############################################################################################################################################################################
# SPRING
##############################################################################################################################################################################
spring.application.name=@project.artifactId@
springdoc.swagger-ui.tagSorter=alpha
springdoc.swagger-ui.doc-expansion=none
##############################################################################################################################################################################
# DATABASE
##############################################################################################################################################################################
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/skills-hub
spring.datasource.username=root
spring.datasource.password=
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.liquibase.enabled=false
#Defalut values configured for MT clusters
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.max-lifetime=1800000
##############################################################################################################################################################################
# WEBSERVICE
##############################################################################################################################################################################
##############################################################################################################################################################################
# COMMIT MESSAGES
##############################################################################################################################################################################
#spring:
#  application:
#    name: skillhub
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: ${DB_DRIVER}
#  rabbitmq:
#    host: ${RABBITMQ_HOST}
#    port: ${RABBITMQ_PORT}
#    username: ${RABBITMQ_USERNAME}
#    password: ${RABBITMQ_PASSWORD}
#
#  liquibase:
#    change-log: ${LIQUIBASE_CHANGELOG}
#
#  servlet:
#    multipart:
#      max-file-size: ${MAX_FILE_SIZE}
#      max-request-size: ${MAX_REQUEST_SIZE}
#
#keycloak:
#  realm: ${KEYCLOAK_REALM}
#  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
#  resource: ${KEYCLOAK_CLIENT_ID}
#  credentials:
#    secret: ${KEYCLOAK_CLIENT_SECRET}
#  jwt:
#    issuer-uri: ${KEYCLOAK_JWT_ISSUER_URI}
#
#aws:
#  s3:
#    bucket-name: ${AWS_S3_BUCKET_NAME}
#    region: ${AWS_REGION}
#    access-key: ${AWS_ACCESS_KEY_ID}
#    secret-key: ${AWS_SECRET_ACCESS_KEY}
#
#custom:
#  storage:
#    type: ${STORAGE_TYPE}
#    local:
#      base-path: ${STORAGE_LOCAL_BASE_PATH}
