server:
  port: 10020

springdoc:
  swagger-ui:
    tagsSorter: alpha
    doc-expansion: none

spring:
  application:
    name: @project.artifactId@

  datasource:
    course:
      url: jdbc:postgresql://localhost:5433/course_service
      username: root
      password: root
    storage:
      url: jdbc:postgresql://localhost:5434/storage_service
      username: root
      password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: false

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin