server:
  port: ${SERVER_PORT:10020}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:skillshub-backend}
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
      file-size-threshold: 5MB

  datasource:
    course:
      url: ${SPRING_DATASOURCE_COURSE_URL:jdbc:postgresql://postgres-course:5432/course_service}
      username: ${SPRING_DATASOURCE_COURSE_USERNAME}
      password: ${SPRING_DATASOURCE_COURSE_PASSWORD}
    user:
      url: ${SPRING_DATASOURCE_USER_URL:jdbc:postgresql://postgres-user:5432/user_service}
      username: ${SPRING_DATASOURCE_USER_USERNAME}
      password: ${SPRING_DATASOURCE_USER_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

rabbitmq:
  host: ${RABBITMQ_HOST:rabbitmq}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USER}
  password: ${RABBITMQ_PASS}
  virtual-host: ${RABBITMQ_VHOST:/}
  connection-timeout: 5000

# ==============================================================
# 🗃️ Course Service RabbitMQ Configuration
# ==============================================================
course:
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:course.events}
    upload-routing-key: ${RABBITMQ_ROUTING_KEY:course.media.uploaded.v1}
    metadata-routing-key: ${RABBITMQ_ROUTING_KEY_METADATA:course.media.metadata.extracted.v1}
    uploaded-queue: ${RABBITMQ_QUEUE_UPLOADED:course.media.uploaded.queue}
    metadata-queue: ${RABBITMQ_QUEUE_METADATA:course.media.metadata.extracted.queue}

# ==============================================================
# 🗃️ User Service
# ==============================================================
user-service:
  base-url: ${USER_SERVICE_BASE_URL:http://backend-service:${SERVER_PORT:10020}}

# ==============================================================
# 📈 Monitoring
# ==============================================================
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:prometheus,health,info}
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# ==============================================================
# 🪵 Logging
# ==============================================================
logging:
  level:
    root: INFO
    com.simplon_project.skillhub: DEBUG
    org.springframework.amqp: INFO
    com.rabbitmq.client: INFO