##############################################################################################################################################################################
# SERVER
##############################################################################################################################################################################
server:
  port=10020
##############################################################################################################################################################################
# SPRING
##############################################################################################################################################################################
springdoc:
  swagger-ui:
    tagSorter=alpha
    doc-expansion=none
spring:
  application:
    name=@project.artifactId@

  ##############################################################################################################################################################################
  # DATABASE
  ##############################################################################################################################################################################
  datasource:
    url=jdbc:mariadb://mariadb:3306/skills-hub
    username=root
    password=
    #Defalut values configured for MT clusters
    hikari.maximum-pool-size=10
    hikari.minimum-idle=3
    hikari.max-lifetime=1800000
  jpa:
    database-platform=org.hibernate.dialect.MariaDBDialect
    open-in-view=false
    properties.hibernate.format_sql=true
  liquibase:
    enabled=false
##############################################################################################################################################################################
# WEBSERVICE
##############################################################################################################################################################################
##############################################################################################################################################################################
# COMMIT MESSAGES
##############################################################################################################################################################################
#spring:
#  application:
#    name: skillhub
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: ${DB_DRIVER}
#  rabbitmq:
#    host: ${RABBITMQ_HOST}
#    port: ${RABBITMQ_PORT}
#    username: ${RABBITMQ_USERNAME}
#    password: ${RABBITMQ_PASSWORD}
#
#  liquibase:
#    change-log: ${LIQUIBASE_CHANGELOG}
#
#  servlet:
#    multipart:
#      max-file-size: ${MAX_FILE_SIZE}
#      max-request-size: ${MAX_REQUEST_SIZE}
#
#keycloak:
#  realm: ${KEYCLOAK_REALM}
#  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
#  resource: ${KEYCLOAK_CLIENT_ID}
#  credentials:
#    secret: ${KEYCLOAK_CLIENT_SECRET}
#  jwt:
#    issuer-uri: ${KEYCLOAK_JWT_ISSUER_URI}
#
#aws:
#  s3:
#    bucket-name: ${AWS_S3_BUCKET_NAME}
#    region: ${AWS_REGION}
#    access-key: ${AWS_ACCESS_KEY_ID}
#    secret-key: ${AWS_SECRET_ACCESS_KEY}
#
#custom:
#  storage:
#    type: ${STORAGE_TYPE}
#    local:
#      base-path: ${STORAGE_LOCAL_BASE_PATH}
